spring:
  application:
    name: turbine

server:
  port: 8088

management:
  port: 8089
  web:
    base-path: /

eureka:
  client:
    service-url:
      defaultZone: http://10.120.66.36:8080/eureka

turbine:
  app-config: as-xm-stag
  cluster-name-expression: new String("default")
  combine-host-port: true
  instanceUrlSuffix: hystrix.stream

