spring:
  application:
    name: eureka-consumer-hystrix

server:
  port: 10012

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 500
  ConnectTimeout: 500
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 1500