spring:
  application:
    name: eureka-consumer-hystrix

server:
  port: 10012

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

feign:
  hystrix:
    enabled: true